---
- name: check host environment
  include: check_environment.yml

- debug:
    var="{{ item }}"
  when: "{{ item }} is defined"
  with_items:
    - oracle_java_cache_valid_time
    - oracle_java_home
    - oracle_java_installed
    - oracle_java_os_supported
    - oracle_java_rpm_filename
    - oracle_java_set_as_default
    - oracle_java_rpm_url
    - oracle_java_state
    - oracle_java_version_build
    - oracle_java_version_installed
    - oracle_java_version_string

- name: Install Java
  include: "install_oracle_java.yml"