---
# This playbook deploys the whole application stack in this site.

# - name: Common Installation/Configuration
#   hosts: localtest
#   roles:
#     - common

# - name: Web servers Installation/Configuration
#   hosts: localtest
#   roles:
#     - web

# - name: Common Installation/Configuration
#   hosts: localtest
#   roles:
#     - ands-registry

# - hosts: localtest
#   roles:
#      - oracle-java

# - name: Redis Installation/Configuration
#   hosts: localtest
#   roles:
#     - redis

- name: Percona
  hosts: localtest
  roles:
    - percona


