---
- name: Add Percona GPG Key
  rpm_key:
    state: present
    key: http://www.percona.com/downloads/RPM-GPG-KEY-percona

- name: Add Percona repository
  copy:
    src: percona.repo
    dest: /etc/yum.repos.d/
    owner: root
    group: root
    mode: 0644

- name: Ensure MySQL server is uninstalled
  yum: pkg={{ item }} state=absent
  with_items:
    - mysql-server-core-5.5
    - mysql-client
    - mysql-client-5.5
    - mysql-client-core-5.5
  register: install_result
  notify:
    - restart percona

- name: Install Percona packages
  yum: pkg={{ item }} state=present update_cache=yes
  with_items:
    - Percona-Server-server-56

- name: Make sure mysql did not start before it is configured
  service: name=mysql state=stopped
  when: install_result|changed

- name: Write custom server configuration
  template: src=etc_mysql_my.cnf.j2 dest=/etc/mysql/my.cnf owner=root mode=0644
  notify:
    - restart percona

- name: MySQL service start
  service:
    name: mysql
    state: started
    enabled: yes

- name: Ensure mysql port is running
  wait_for: port={{ mysql_port }} state=started timeout=30