---
- name: Install Webtatic repo.
  yum:
    name: "{{ webtatic_repo_url | default(repo_by_version[ansible_distribution_major_version | int]) }}"
    state: present

- name: Import Webtatic GPG key.
  rpm_key:
    key: "{{ webtatic_repo_gpg_key_url | default(key_by_version[ansible_distribution_major_version | int]) }}"
    state: present

- name: Check if EPEL repo is already configured.
  stat: path={{ epel_repofile_path }}
  register: epel_repofile_result

- name: Install EPEL repo.
  yum:
    name: "{{ epel_repo_url }}"
    state: present
  register: result
  until: '"failed" not in result'
  retries: 5
  delay: 10
  when: not epel_repofile_result.stat.exists

- name: Import EPEL GPG key.
  rpm_key:
    key: "{{ epel_repo_gpg_key_url }}"
    state: present
  when: not epel_repofile_result.stat.exists
  ignore_errors: "{{ ansible_check_mode }}"